version: '3.8'

services:
  laravel:
    restart: unless-stopped
    container_name: laravelapp
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../storage/app:/var/www/html/storage/app
    ports:
      - "8080:80"
    env_file:
      - .env   # This assumes your Laravel .env file is located at the same level as your docker-compose.yml or adjust the path accordingly.
    networks:
      - n-laravel

networks:
  n-laravel:
    driver: bridge
