version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    container_name: laravel-builder
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
    env_file:
      - .env
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: laravel-php
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
    env_file:
      - .env
    expose:
      - 9000
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
